#include <string.h>
#include "mongoose.h"

void asteroid_native_http_request_handler(struct mg_connection *c, struct http_message *hm)
{
	const char say[] = "<h1>Hello world!</h1>\
	<p>This dynamic page is generated by a native C program</p>";
	mg_send_head(c, 200, strlen(say), "Content-Type: text/html");
	mg_printf(c, say);
}