#include <string.h>
#include "mongoose.h"

void native_home_page(struct mg_connection *c)
{
	const char say[] = "<h1>Native Page</h1>\
	<p>This dynamic page is generated by a native C program</p>";
	mg_send_head(c, 200, strlen(say), "Content-Type: text/html");
	mg_printf(c, say);
	return;
}

void asteroid_native_http_request(struct mg_connection *c, struct http_message *hm, char *rewrite)
{
	if (hm->uri.len == 1) {
		//native_home_page(c);
		strcpy(rewrite, "/home.lua");
		return;
	}
	const char say[] = "<h1>Hello world!</h1>\
	<p>This dynamic page is generated by a native C program</p>";
	mg_send_head(c, 200, strlen(say), "Content-Type: text/html");
	mg_printf(c, say);
}