echo(env.raw())
echo(env.uri())
echo(env.content_len())
echo(env.content_type())
echo(env.origin())
echo(env.ua())
echo(env.host())
echo(env.encoding())
echo(env.lang())
echo(env.accept())
echo(env.body())

flush('Content-Type: text/plain')
--flush('Content-Type: text/html')