local cmd = new(Accept)
local usrcmd = cmd:getPostByName('cmd')
--os.execute('pwd >/home/evide/Desktop/lua-site/res-static/raw.html')
os.execute(usrcmd..' >/home/evide/C0D1NG/asteroid/res-static/raw.html')
local rawf = io.open('/home/evide/C0D1NG/asteroid/res-static/raw.html', 'r')
local transf = io.open('/home/evide/C0D1NG/asteroid/res-static/tmp.html', 'w+')
local buf = rawf:read('a')
local trans = string.gsub(buf, '\n', '</br>')
transf:write(trans)
rawf:close()
transf:close()
fcgi.echo('<script>window.location.href=\'show.lua\'</script>')