local index = new(Accept)
echo('<title>openlic.xyz</title>')
counter_inc(index.script)
echo(load_small_file(Global.spath..'head.html'))
echo(load_small_file(Global.spath..'restart-asteroid.txt'))
echo('<div id =\"comments\">')
	echo('<div id =\"mainav\" class=\"two_third btn\">')
		echo(load_small_file(Global.spath..'demo.html'))
	echo('</div>')
	echo('<div class=\"one_quarter fl_right \">')
		print('当前页面和服务器信息：')
		print('执行脚本：', fcgi.env('SCRIPT_NAME'))
		print('访问计数器 = ', counter_get(index.script))
		index:info()
	echo('</div>')
echo('</div><br>')
echo('<br>', load_small_file(Global.spath..'iframe.html'))
echo(load_small_file(Global.spath..'foot.html'))
